services:
  web:
    build: 
      context: ./backend
    container_name: web
    volumes:
      - ./backend/django:/project
      - ./nginx/certs:/etc/ssl/certs
      - ./staticfiles:/project/staticfiles
    env_file:
      - .env
    networks:
      - Transcendence-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "5000:443"
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - ./staticfiles:/project/staticfiles
    env_file:
      - .env
    networks:
      - Transcendence-network
    depends_on:
      - web

networks:
  Transcendence-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
