services:
  db:
    build: ./database
    container_name: postgresql
    env_file:
      - ./.env
    networks:
      - Transcendence-network

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   networks:
  #     - Transcendence-network

  web:
    build: ./backend
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - ./backend/django:/project
    env_file:
      - .env
    networks:
      - Transcendence-network
    depends_on:
      - db

networks:
  Transcendence-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
