services:
  db:
    build: 
      context: ./database
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        DB_PSSWRD: ${DB_PSSWRD}
    container_name: postgresql
    env_file:
      - .env
    networks:
      - Transcendence-network
    healthcheck:
      #test: ["CMD", "su", "postgres", "-c", "psql -l"]
      #test: ["CMD", "pg_isready"]
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres", "--port=5432"]
      interval: 5s
      timeout: 5s
      retries: 7

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   networks:
  #     - Transcendence-network

  web:
    build: ./backend
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - ./backend/django:/project
    env_file:
      - .env
    networks:
      - Transcendence-network
    depends_on:
      db:
        condition: service_healthy

networks:
  Transcendence-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
