version: '3.8'

services:
#  db:
#    image: postgres:13
#    container_name: db
#    environment:
#      - .env
#    volumes:
#      - ~./sgoinfre/postgres_data:/var/lib/postgresql/data
#    networks:
#      - Transcendence-network

  web:
    build: ./backend
    container_name: web
    ports:
      - "8081:8081"
    #command: python manage.py runserver 0.0.0.0:8000
    #volumes:
     # - ./project:/app
    environment:
      - .env
    networks:
      - Transcendence-network
    #depends_on:
     # - db

#  #frontend:
#    image: nginx:latest
#    volumes:
#      - ./frontend:/usr/share/nginx/html:ro
#    networks:
#      - Transcendence-network
#    ports:
#      - "8080:80"
#    depends_on:
#      - web

networks:
  Transcendence-network: