services:
  web:
    build: 
      context: ./backend
    container_name: web
    volumes:
      - ./backend/django:/project
      - ./staticfiles:/project/staticfiles
    env_file:
      - .env
    networks:
      - Transcendence-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "5000:443"
    volumes:
      - ./staticfiles:/project/staticfiles
    env_file:
      - .env
    networks:
      - Transcendence-network
    depends_on:
      web: 
        condition: service_healthy

networks:
  Transcendence-network:
    ipam:
      config:
        - subnet: 172.18.0.0/24
