# Generated by Django 4.2.15 on 2024-08-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_authenticated',
        ),
    ]
