# Generated by Django 4.2.15 on 2024-08-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_data',
        ),
    ]
