# Generated by Django 4.2.15 on 2024-08-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userregister_is_anonymous_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuth2User',
        ),
    ]
