# Generated by Django 4.2.15 on 2024-08-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_oauth2user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='online',
        ),
    ]
