# Generated by Django 4.2.15 on 2024-08-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userregister_response_headers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='response_headers',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='response_json',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='response_text',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='status_code',
        ),
    ]
