# Generated by Django 4.2.15 on 2024-08-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_userregister_response_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='response_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='response_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='response_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userregister',
            name='status_code',
            field=models.IntegerField(default=int),
        ),
    ]
