# Generated by Django 4.2.16 on 2024-10-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userregister_response_headers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
